### ISSUE TITLE
Error creating the cluster

### ISSUE THREAD

**Issue by gilblau** [sobotklp/kubernetes-redis-cluster#7]
Hi,

I am trying to deploy on google k8s, but I keep getting the following error:

- '/bin/peer-finder' saved [2987890/2987890]
lookup redis-cluster on XX.X.XXX.XX:XX: no such host
...
Peer list updated
was []
now [redis-cluster-0.redis-cluster.redis-cluster.svc.cluster.local]
execing: tee &gt; /conf/initial_peers with stdin: redis-cluster-0.redis-cluster.redis-cluster.svc.cluster.local
Failed to execute tee &gt; /conf/initial_peers: bash: /conf/initial_peers: Read-only file system
, err: exit status 1

Anyone has an idea how this can be resolved?

**Comment by gilblau** [comment]
FYI - I have done some modifications to resolve this issue and added support for PVC, I will create a fork...

**Comment by mrhjx2** [comment]
hi i get the same issue. do you get it?

**Comment by tsu710785** [comment]
What version of k8s did u use? 
I thought that is because k8s feature introduced in V1.9.4, which change volumes to read only.
ref: https://github.com/kubernetes/kubernetes/pull/58720

My solution is using k8s local dns to find peer instead. Can take a look of bootstrap-pod.sh I changed here. But after getting peer ip, I still have some issue to fix cluster now.
https://github.com/tsu710785/kubernetes-redis-cluster
